{"uuid": "6f25711c-7f3a-480d-9f6a-a9ea572b06c4", "children": ["590b7461-b277-47b8-8821-f9557554293f", "38178e0c-a07f-493a-8ed8-ec13bdd041b2", "5ac094a1-306c-4a60-96f8-8da4d9883813", "3e64ccb7-fa63-457c-af03-b4ac59a981be", "cf5601f0-9e68-4e55-98e0-5f7cd03f1a8c", "9dc4115a-6657-4d57-8d34-829e3fcb15b3", "6e0f8f50-ef38-448f-8882-259380bc810c"], "befores": [{"name": "xunit_setup_class_fixture_TestUser", "status": "passed", "start": 1627893817140, "stop": 1627893817140}], "afters": [{"name": "xunit_setup_class_fixture_TestUser::0", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1\")\n", "trace": "  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\_pytest\\python.py\", line 815, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\shj\\YT_interface2\\testcase\\test_set.py\", line 293, in teardown_class\n    self.sql_exec.update(self.sql['user']['clear_relate'].format(userId_tuple))\n  File \"F:\\shj\\YT_interface2\\common\\execSql.py\", line 63, in update\n    self.cur.execute(sql)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 148, in execute\n    result = self._query(query)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 310, in _query\n    conn.query(q)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 775, in _read_query_result\n    result.read()\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 725, in _read_packet\n    packet.raise_for_error()\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\n"}, "start": 1627893817143, "stop": 1627893817651}], "start": 1627893817140, "stop": 1627893817651}