[2021-08-10 09:35:47,336]-logs.py]-ERROR:登录报错HTTPSConnectionPool(host='mytest.ytoglobal.com', port=8080): Max retries exceeded with url: /gateway/app/user/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004191388>: Failed to establish a new connection: [Errno 10060] ',))
