{"status": "broken", "uuid": "e3542567-7407-4924-995f-52f407d7f17c", "labels": [{"name": "story", "value": "更新api数据接口"}, {"name": "feature", "value": "API设置"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestAPI"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "4156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1628559347422, "testCaseId": "03e180dbd144c07301563e717987273b", "historyId": "79d593ef6d849f17fed597f8ab803208", "start": 1628559347422, "fullName": "testcase.test_set.TestAPI#test_api_update", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_api_update"}